
export const data = [
  //  Men
  {
    id: 1,
    name: "Men's Casual T-Shirt",
    image: "https://images.unsplash.com/photo-1521572163474-6864f9cf17ab",
    price: 14.99,
    description: "Cotton round-neck casual t-shirt, slim fit.",
    category: "Men",
    size: ["S", "M", "L", "XL"],
    color: ["White", "White", "Blue"],
    quantity: 1,
  },
  {
    id: 2,
    name: "Men's Denim Jeans",
    image: "https://images.unsplash.com/photo-1541099649105-f69ad21f3246",
    price: 34.99,
    description: "Classic blue straight-fit denim jeans.",
    category: "Men",
    size: ["30", "32", "34", "36"],
    color: ["Blue"],
    quantity: 1,

  },
  {
    id: 3,
    name: "Men's Formal Shirt",
    image: "https://dfcdn.defacto.com.tr/3/D3673AX_25SM_KH202_01_01.jpg",
    price: 27.5,
    description: "Button-up slim-fit formal shirt.",
    category: "Men",
    size: ["M", "L", "XL"],
    color: ["green", "Light Blue"],
    quantity: 1,

  },
  {
    id: 4,
    name: "Men's Leather Jacket",
    image: "https://dfcdn.defacto.com.tr/responsive/navigasyon/v5/erkek/subat25/studio.png",
    price: 89.99,
    description: "Classic black leather biker jacket.",
    category: "Men",
    size: ["M", "L", "XL"],
    color: ["Black"],
    quantity: 1,

  },
  

  
  {
    id: 6,
    name: "Women's Summer Dress",
    image: "https://dfcdn.defacto.com.tr/3/D4145AX_25AU_YL508_01_01.jpg",
    price: 39.99,
    description: "Lightweight floral print summer dress.",
    category: "Women",
    size: ["S", "M", "L"],
    color: ["Yellow", "Green"],
    quantity: 1,

  },
  {
    id: 7,
    name: "Women's Blouse",
    image: "https://dfcdn.defacto.com.tr/responsive/navigasyon/v5/kadin/subat25/ofis.png",
    price: 22.0,
    description: "Elegant chiffon blouse with long sleeves.",
    category: "Women",
    size: ["S", "M", "L", "XL"],
    color: ["White", "Pink", "Black"],
    quantity: 1,

  },
  {
    id: 8,
    name: "Women's Skirt",
    image: "https://images.unsplash.com/photo-1503342217505-b0a15ec3261c",
    price: 29.5,
    description: "High-waist pleated midi skirt.",
    category: "Women",
    size: ["S", "M", "L"],
    color: ["Navy", "Beige"],
    quantity: 1,

  },
  {
    id: 9,
    name: "Women's Cardigan",
    image: "https://images.unsplash.com/photo-1512436991641-6745cdb1723f",
    price: 35.0,
    description: "Soft knit open-front cardigan.",
    category: "Women",
    size: ["S", "M", "L", "XL"],
    color: ["Beige", "Grey"],
    quantity: 1,
  },
  

  // 🧒 Kids
  {
    id: 11,
    name: "Kids T-Shirt",
    image: "https://dfcdn.defacto.com.tr/ResponsiveFashion/menuler/yeni%20men%C3%BC%20g%C3%B6rselleri/GIRL/%C5%9Fapka.jpg",
    price: 12.99,
    description: "Cotton printed t-shirt for kids.",
    category: "Kids",
    size: ["2Y", "4Y", "6Y", "8Y", "10Y"],
    color: ["Blue", "Yellow", "Red"],
    quantity: 1,
  },
  {
    id: 12,
    name: "Kids Denim Jacket",
    image: "https://images.unsplash.com/photo-1603252109303-2751441dd157",
    price: 25.99,
    description: "Stylish denim jacket for boys and girls.",
    category: "Kids",
    size: ["4Y", "6Y", "8Y", "10Y", "12Y"],
    color: ["Blue", "Black"],
    quantity: 1,
  },
  {
    id: 13,
    name: "Kids Summer Dress",
    image: "https://dfcdn.defacto.com.tr/ResponsiveFashion/menuler/yeni%20men%C3%BC%20g%C3%B6rselleri/GIRL/elbise.jpg",
    price: 19.99,
    description: "Colorful cotton summer dress for girls.",
    category: "Kids",
    size: ["2Y", "4Y", "6Y", "8Y"],
    color: ["Pink", "Yellow"],
    quantity: 1,
  },
  {
    id: 14,
    name: "Kids Shorts",
    image: "https://dfcdn.defacto.com.tr/responsive/navigasyon/v5/kiz-bebek/subat25/yenidogan/pamuk1.jpg",
    price: 15.5,
    description: "Casual cotton shorts for boys.",
    category: "Kids",
    size: ["4Y", "6Y", "8Y", "10Y"],
    color: ["Navy", "Beige"],
    quantity: 1,
  },

  // 👟 Accessories
  {
    id: 15,
    name: " Sneakers",
    image: "https://dfcdn.defacto.com.tr/Mobile/en_accessories_1320x580-desktop_963b86c7-4094-4dbd-b817-babdd41b25a0_9ecc9716-e5de-4fed-8f5b-47a79c4ce763_DI_429.jpg",
    price: 39.99,
    description: "Comfortable everyday sneakers.",
    category: "Accessories",
    size: ["38", "39", "40", "41", "42", "43", "44"],
    color: ["White", "Black"],
    quantity: 1,
  },
  {
    id: 16,
    name: "Leather Handbag",
    image: "https://images.unsplash.com/photo-1584917865442-de89df76afd3",
    price: 59.99,
    description: "Premium quality leather handbag.",
    category: "Accessories",
    size: ["One"],
    color: ["Red", "Black"],
    quantity: 1,
  },
  {
    id: 17,
    name: "Baseball Cap",
    image: "https://dfcdn.defacto.com.tr/7/D7820AX_25SM_BG376_01_01.jpg",
    price: 15.0,
    description: "Classic cotton adjustable cap.",
    category: "Accessories",
    size: ["One"],
    color: ["beige", "White", "Grey"],
    quantity: 1,
  },
  
  {
    id: 19,
    name: "Sunglasses",
    image: "https://images.unsplash.com/photo-1503341455253-b2e723bb3dbb",
    price: 24.99,
    description: "UV-protected stylish sunglasses.",
    category: "Accessories",
    size: ["One"],
    color: ["Black", "Brown"],
    quantity: 1,
  },
];
